name: Generate Word of the Day

on:
  schedule:
    - cron: "0 6 * * *" # Runs every day at 06:00 UTC
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write # Needed so Actions can push changes

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python generate_word_of_the_day.py

      - name: Commit & push changes
        run: |
          git config --global user.name "An009"
          git config --global user.email "kreechanouar@gmail.com"
          git add .
          git commit -m "feat: Add Word of the Day for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git pull --rebase origin main
          git push
